name = "HybridBlockArrays"
uuid = "c01b3b2d-6ffc-4f93-8ae5-34077a31c86c"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.1.0"

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
